version: "3"
services:
  nas-tools:
    image: nastools/nas-tools:latest #若使用最新镜像请改为jxxghp/nas-tools:latest
    ports:
      - 3000:3000 # 默认的webui控制端口
    volumes:
      - ./nastool_config:/config # 冒号左边请修改为你想保存配置的路径
      - ./downloads:/downloads #设置下载路径
      - /root/.config/rclone:/root/.config/rclone #rclone配置文件映射
      - /mnt:/mnt
    environment:
      - PUID=0 # 想切换为哪个用户来运行程序，该用户的uid
      - PGID=0 # 想切换为哪个用户来运行程序，该用户的gid
      - UMASK=000 # 掩码权限，默认000，可以考虑设置为022
      - NASTOOL_AUTO_UPDATE=false # 如需在启动容器时自动升级程程序请设置为true
      - NASTOOL_CN_UPDATE=false # 如果开启了容器启动自动升级程序，并且网络不太友好时，可以设置为true，会使用国内源进行软件更新
      #- REPO_URL=https://ghproxy.com/https://github.com/NAStool/nas-tools.git  # 当你访问github网络很差时，可以考虑解释本行注释
    restart: always
    network_mode: bridge
    hostname: nas-tools
    container_name: nas-tools
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai # 你的时区
      - UMASK_SET=000
      - WEBUI_PORT=58080 # 将此处修改成你欲使用的 WEB 管理平台端口 
    volumes:
      - ./qb_config:/config # 绝对路径请修改为自己的config文件夹
      - ./downloads:/downloads # 绝对路径请修改为自己的downloads文件夹
    ports:
      # 要使用的映射下载端口与内部下载端口，可保持默认，安装完成后在管理页面仍然可以改成其他端口。
      - 56881:56881
      - 56881:56881/udp
      # 此处WEB UI 目标端口与内部端口务必保证相同，见问题1
      - 58080:58080
    restart: unless-stopped
    
