version: "3"
services:
  moviepilot:
    image: jxxghp/moviepilot:latest
    ports:
      - 3000:3000 # 默认的webui控制端口
      - 3001:3001 # 默认的api端口
    volumes:
      - ./mp_data:/config # 冒号左边请修改为你想保存配置的路径
      - ./downloads:/downloads #设置下载路径
      - /root/.config/rclone:/mp/.config/rclone #rclone配置文件映射
    environment:
      - TZ=Asia/Shanghai
      - NGINX_PORT=3000
      - PORT=3001
      - MOVIEPILOT_AUTO_UPDATE=false
      - SUPERUSER= # 超级管理员用户名
      - SUPERUSER_PASSWORD= # 超级管理员密码
      - API_TOKEN= # API密钥
      - AUTH_SITE=audiences # 认证站点
      - AUDIENCES_UID= # 认证站点UID
      - AUDIENCES_PASSKEY= # 认证站点Passkey
      - BIG_MEMORY_MODE=true
      - RCLONE_TRANSFERS=8
    restart: unless-stopped
    container_name: moviepilot
  qbittorrent:
    image: linuxserver/qbittorrent:4.5.2
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai # 你的时区
      - UMASK_SET=000
      - WEBUI_PORT=58080 # 将此处修改成你欲使用的 WEB 管理平台端口 
    volumes:
      - ./qb_data:/config # 绝对路径请修改为自己的config文件夹
      - ./downloads:/downloads # 绝对路径请修改为自己的downloads文件夹
    ports:
      - 58080:58080 # GUI
      # 要使用的映射下载端口与内部下载端口，可保持默认，安装完成后在管理页面仍然可以改成其他端口。
      - 56881:56881
      - 56881:56881/udp
      # 此处WEB UI 目标端口与内部端口务必保证相同，见问题1
    restart: unless-stopped
    
